# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          # From https://github.com/actions/checkout/issues/116#issuecomment-583221947
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule sync --recursive
          git -c "http.extraheader=Authorization: basic ${{secrets.GITHUB_ACCESS_TOKEN}}" -c protocol.version=2 submodule update --init --force --recursive --depth=1


      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: $GITHUB_REPOSITORY_NAME
          path: "*"
